<a href="https://colab.research.google.com/github/PallaviLakhe22/Credit-Card-Fraud-Detection-Model/blob/main/Credit_Card_Fraud_Detection_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_card.csv')

In [4]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
194715,130729.0,-2.639901,-2.299147,-0.431549,0.989190,3.922966,-0.609333,-0.559169,0.520055,-0.073139,...,0.307557,0.052561,0.708417,-0.535599,0.191581,-0.040650,0.042709,0.239706,181.92,0.0
194716,130730.0,1.626344,-0.714900,-0.076799,1.276011,-0.672945,0.460552,-0.698794,0.247377,0.861302,...,0.186074,0.328603,0.182371,0.730497,-0.399588,-0.826018,0.044937,0.001702,144.00,0.0
194717,130730.0,-1.790520,0.402734,-2.645359,0.306589,-1.007085,-0.952446,0.830407,0.706309,0.030736,...,0.045062,0.313472,0.660812,-0.108394,-1.913863,-0.371357,0.123747,-0.255891,232.87,0.0
194718,130730.0,-1.491244,1.739073,1.123336,-1.771267,1.574772,-0.033488,2.198822,-2.102641,3.405287,...,-0.841096,-0.633202,-0.418964,-1.145617,-0.008533,-0.515810,-1.526798,-1.542355,0.77,0.0
194719,130731.0,0.021815,0.270965,1.012959,-0.410929,-0.483813,0.388497,-0.405355,0.082671,-1.433698,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194720 entries, 0 to 194719
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    194720 non-null  float64
 1   V1      194720 non-null  float64
 2   V2      194720 non-null  float64
 3   V3      194720 non-null  float64
 4   V4      194720 non-null  float64
 5   V5      194720 non-null  float64
 6   V6      194720 non-null  float64
 7   V7      194720 non-null  float64
 8   V8      194720 non-null  float64
 9   V9      194720 non-null  float64
 10  V10     194720 non-null  float64
 11  V11     194720 non-null  float64
 12  V12     194720 non-null  float64
 13  V13     194720 non-null  float64
 14  V14     194720 non-null  float64
 15  V15     194720 non-null  float64
 16  V16     194720 non-null  float64
 17  V17     194720 non-null  float64
 18  V18     194719 non-null  float64
 19  V19     194719 non-null  float64
 20  V20     194719 non-null  float64
 21  V21     194719 non-null  float64
 22  V22     194719 non-null  float64
 23  V23     194719 non-null  float64
 24  V24     194719 non-null  float64
 25  V25     194719 non-null  float64
 26  V26     194719 non-null  float64
 27  V27     194719 non-null  float64
 28  V28     194719 non-null  float64
 29  Amount  194719 non-null  float64
 30  Class   194719 non-null  float64
dtypes: float64(31)
memory usage: 46.1 MB

In [7]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [8]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    194338
1.0       381
Name: Class, dtype: int64

In [9]:
#   0 --> Normal Transaction

#   1 --> fraudulent transaction

In [10]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
print(legit.shape)
print(fraud.shape)

(194338, 31)
(381, 31)

In [12]:
# statistical measures of the data
legit.Amount.describe()

count    194338.000000
mean         89.431093
std         248.533872
min           0.000000
25%           5.990000
50%          22.910000
75%          79.000000
max       19656.530000
Name: Amount, dtype: float64

In [13]:
fraud.Amount.describe()

count     381.000000
mean      116.421155
std       247.034583
min         0.000000
25%         1.000000
50%        11.400000
75%       104.030000
max      2125.870000
Name: Amount, dtype: float64

In [14]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,68996.888164,-0.103089,-0.000960,0.362227,0.074162,-0.113649,0.051488,-0.042865,0.018610,0.015720,...,0.020694,-0.017908,-0.053359,-0.017011,0.005005,0.065334,0.007082,0.000978,0.002041,89.431093
1.0,60541.997375,-5.755911,4.243874,-7.768470,4.780104,-4.143295,-1.408967,-6.702717,0.703757,-2.780511,...,0.382486,0.798233,-0.021515,-0.038763,-0.066856,0.074069,0.041146,0.177640,0.056083,116.421155

In [15]:
#Under-Sampling

In [16]:
#Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

In [17]:
#Number of Fraudulent Transactions --> 492

In [18]:
legit_sample = legit.sample(n=492)

In [19]:
#Concatenating two DataFrames

In [20]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [21]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
59066,48679.0,-3.198713,0.204363,-0.611878,-2.582008,-2.315844,0.158001,-1.663829,2.047428,-2.146675,...,-0.363930,-0.803873,0.235532,-0.951534,0.039442,-0.438396,0.426293,-0.261814,84.00,0.0
176857,122942.0,-2.479121,2.506733,-0.422576,-1.766444,0.484753,0.179024,0.443437,-0.046416,2.348983,...,-0.505029,-0.892900,-0.130281,-1.556403,0.320774,-0.247076,0.262450,0.345608,0.77,0.0
113284,73006.0,-0.649102,-0.297479,1.027609,-0.518064,2.648798,3.653299,-0.883381,0.992228,0.213006,...,0.324098,0.831521,-0.105721,1.007612,-0.365599,-0.379887,0.041064,-0.032861,2.63,0.0
40850,40427.0,-10.710076,5.400962,-1.795264,-1.912557,-2.526976,-0.518293,2.675228,-1.175406,9.112555,...,-2.518495,-0.020931,0.163237,0.913667,1.822053,0.109292,0.681943,-0.531721,219.82,0.0
54404,46436.0,-0.658542,1.088460,0.187729,0.039985,2.916196,3.697344,0.424799,0.908744,-1.290712,...,-0.006435,-0.346302,-0.168871,0.960620,-0.000850,-0.309331,-0.046193,0.121791,14.22,0.0

In [22]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
191690,129371.0,1.183931,3.057250,-6.161997,5.543972,1.617041,-1.848006,-1.005508,0.339937,-2.959806,...,0.109185,-0.931072,-0.064175,-0.007013,0.345419,0.064558,0.476629,0.323740,0.00,1.0
192382,129668.0,0.753356,2.284988,-5.164492,3.831112,-0.073622,-1.316596,-1.855495,0.831079,-1.567514,...,0.382007,0.033958,0.187697,0.358433,-0.488934,-0.258802,0.296145,-0.047174,2.00,1.0
192529,129741.0,-1.396204,2.618584,-6.036770,3.552454,1.030091,-2.950358,-1.528506,0.189319,-1.433554,...,0.143177,-0.390176,0.356029,-0.762352,0.096510,-0.487861,0.062655,-0.240732,1.00,1.0
192584,129764.0,-2.434004,3.225947,-6.596282,3.593161,-1.079452,-1.739741,-0.047420,0.301424,-1.779434,...,-0.035491,-0.419178,0.157436,-0.714849,0.468859,-0.348522,0.420036,-0.327643,362.55,1.0
192687,129808.0,1.522080,-0.519429,-2.581685,0.774741,0.206722,-1.431020,0.757011,-0.444418,0.997921,...,0.019649,-0.211678,-0.247452,-0.279472,0.239646,-0.508398,-0.015551,0.041881,276.17,1.0

In [23]:
new_dataset['Class'].value_counts()

0.0    492
1.0    381
Name: Class, dtype: int64

In [24]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,69563.569106,-0.058744,-0.007473,0.461203,0.097156,-0.060805,0.105064,-0.043333,-0.087145,-0.002357,...,-0.004220,-0.037948,-0.044826,0.018835,0.010758,0.095674,0.015524,-0.005561,0.000345,81.521098
1.0,60541.997375,-5.755911,4.243874,-7.768470,4.780104,-4.143295,-1.408967,-6.702717,0.703757,-2.780511,...,0.382486,0.798233,-0.021515,-0.038763,-0.066856,0.074069,0.041146,0.177640,0.056083,116.421155

In [25]:
#Splitting the data into Features & Targets
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [26]:
print(X)

            Time         V1        V2        V3        V4        V5        V6  \
59066    48679.0  -3.198713  0.204363 -0.611878 -2.582008 -2.315844  0.158001
176857  122942.0  -2.479121  2.506733 -0.422576 -1.766444  0.484753  0.179024
113284   73006.0  -0.649102 -0.297479  1.027609 -0.518064  2.648798  3.653299
40850    40427.0 -10.710076  5.400962 -1.795264 -1.912557 -2.526976 -0.518293
54404    46436.0  -0.658542  1.088460  0.187729  0.039985  2.916196  3.697344
...          ...        ...       ...       ...       ...       ...       ...
191690  129371.0   1.183931  3.057250 -6.161997  5.543972  1.617041 -1.848006
192382  129668.0   0.753356  2.284988 -5.164492  3.831112 -0.073622 -1.316596
192529  129741.0  -1.396204  2.618584 -6.036770  3.552454  1.030091 -2.950358
192584  129764.0  -2.434004  3.225947 -6.596282  3.593161 -1.079452 -1.739741
192687  129808.0   1.522080 -0.519429 -2.581685  0.774741  0.206722 -1.431020

              V7        V8        V9  ...       V20       V21       V22  \
59066  -1.663829  2.047428 -2.146675  ... -0.625759 -0.363930 -0.803873
176857  0.443437 -0.046416  2.348983  ...  1.158826 -0.505029 -0.892900
113284 -0.883381  0.992228  0.213006  ...  0.292618  0.324098  0.831521
40850   2.675228 -1.175406  9.112555  ...  3.192540 -2.518495 -0.020931
54404   0.424799  0.908744 -1.290712  ... -0.116464 -0.006435 -0.346302
...          ...       ...       ...  ...       ...       ...       ...
191690 -1.005508  0.339937 -2.959806  ...  0.252571  0.109185 -0.931072
192382 -1.855495  0.831079 -1.567514  ...  0.285792  0.382007  0.033958
192529 -1.528506  0.189319 -1.433554  ...  0.031795  0.143177 -0.390176
192584 -0.047420  0.301424 -1.779434  ... -0.280533 -0.035491 -0.419178
192687  0.757011 -0.444418  0.997921  ...  0.361169  0.019649 -0.211678

             V23       V24       V25       V26       V27       V28  Amount
59066   0.235532 -0.951534  0.039442 -0.438396  0.426293 -0.261814   84.00
176857 -0.130281 -1.556403  0.320774 -0.247076  0.262450  0.345608    0.77
113284 -0.105721  1.007612 -0.365599 -0.379887  0.041064 -0.032861    2.63
40850   0.163237  0.913667  1.822053  0.109292  0.681943 -0.531721  219.82
54404  -0.168871  0.960620 -0.000850 -0.309331 -0.046193  0.121791   14.22
...          ...       ...       ...       ...       ...       ...     ...
191690 -0.064175 -0.007013  0.345419  0.064558  0.476629  0.323740    0.00
192382  0.187697  0.358433 -0.488934 -0.258802  0.296145 -0.047174    2.00
192529  0.356029 -0.762352  0.096510 -0.487861  0.062655 -0.240732    1.00
192584  0.157436 -0.714849  0.468859 -0.348522  0.420036 -0.327643  362.55
192687 -0.247452 -0.279472  0.239646 -0.508398 -0.015551  0.041881  276.17

[873 rows x 30 columns]

In [27]:
print(Y)

59066     0.0
176857    0.0
113284    0.0
40850     0.0
54404     0.0
         ...
191690    1.0
192382    1.0
192529    1.0
192584    1.0
192687    1.0
Name: Class, Length: 873, dtype: float64

In [28]:
#Split the data into Training data & Testing Data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [29]:
print(X.shape, X_train.shape, X_test.shape)

(873, 30) (698, 30) (175, 30)

In [30]:
#Model Training
#Logistic Regression

In [31]:
model = LogisticRegression()

In [32]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

In [33]:
#Model Evaluation
#Accuracy Score

In [34]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [35]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9527220630372493

In [36]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [37]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9371428571428572